### ISSUE TITLE
Model Creation Broken when using Nested Keys

### ISSUE THREAD

**Issue by TechMachineX** [ngx-formly/ngx-formly#1457]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request
```

**Current behavior**
model created in 5.0.0-rc.9 is wrong compared to what was generated in 4.8.2 when using nested (dot notation) as the key.

working (v4.8.2): https://stackblitz.com/edit/angular-b8jgkj?file=src%2Fapp%2Fapp.component.ts
non-working (v5.0.0-rc.9): https://stackblitz.com/edit/angular-nzyrd7?file=src/app/app.component.ts

notice in the non-working one the model is wrong and throwing errors and data capture is not possible.

**Expected behavior**
model should be generated the same as 4.8.2 and allow data capture.

**Minimal reproduction of the problem with instructions**
working(v4.8.2): https://stackblitz.com/edit/angular-b8jgkj?file=src%2Fapp%2Fapp.component.ts
non-working (v5.0.0-rc.9): https://stackblitz.com/edit/angular-nzyrd7?file=src/app/app.component.ts

**Comment by aitboudad** [comment]
fixed in `5.0.0-rc.10`

**Comment by HarshitChhipa** [comment]
What was the solution to this problem?
I too am getting the same issue.
Updated to 5.0.0-rc.12 and still having the issue any idea how to solve.

**Comment by aitboudad** [comment]
@HarshitChhipa could you please provide me a reproduction example, thanks!
