### ISSUE TITLE
Step by Step Form with hideExpressions

### ISSUE THREAD

**Issue by pascalbe-dev** [ngx-formly/ngx-formly#2036]
First of all, thanks for the quick bugfixes and feedbacks, that you give. This is awesome.

**Question**
I want to create some kind of step by step form. The user has multiple clusters (containers for form fields) to fill out. The second one becomes visible, when the first one was filled out. 
I got that working. It's a bit dirty (by accessing private variables) but it works (better approaches welcome).

My problem and question appears, when the several form fields within one cluster also become dependent on each other. User should only see 2nd form field, when the 1st form field was set.

Implementing this feature breaks the cluster step by step, because right after filling the 1st form field, the whole cluster is seen as valid before the 2nd form field appears, which then causes the cluster to become invalid again. I got the `checkExpressionOn: 'modelChange'` extra set, because in our real (huge) app, we have some performance issues which slow down our test execution drastically.

Do you have an idea, how to avoid that behavior? 

I hope, my intent becomes clear with this [Stackblitz.](https://stackblitz.com/edit/ngx-formly-ui-material-quwx1f)
### Repro Steps:
* Fill out Field 'Input'
* Fill out Field 'Textarea' with one letter
### Wanted behavior:
* Field 'Textarea 2' appear, Cluster 2 does not appear
### Actual behavior: 
* Field 'Textarea 2' appear, Cluster 2 appear aswell

**Comment by aitboudad** [comment]
Before going further in your approach, have you considered creating a `stepper` type https://stackblitz.com/edit/angular-yu7bzv-uucyxg, in this example, we rely on `mat-step` but you can create your own stepper.

> I got the checkExpressionOn: 'modelChange' extra set

performance matter, probably it'll be the default behavior in `v6` + OnPush ChangeDetection is coming too.

**Comment by pascalbe-dev** [comment]
> performance matter, probably it'll be the default behavior in v6 + OnPush ChangeDetection is coming too.

Good to know.:)

Thanks for your proposal. In our case, this cluster below cluster approach with some unfancy UI is explicitly wanted. So, some nice looking material stepper is no option.

**Comment by aitboudad** [comment]
Ok sound good, the `stepper` type would allow much more flexibility and avoid relying on private variables 👍.

> My problem and question appears, when the several form fields within one cluster also become dependent on each other. User should only see 2nd form field, when the 1st form field was set.

similar to #2031 which is already fixed, expect a release `Monday`.

**Comment by pascalbe-dev** [comment]
@aitboudad 
The release fixed the other issue I posted lately. That's great. 

However, this issue / question was not fixed with that. I had a look at your stepper solution again, updated to 5.5.10 and added the `checkExpressionOn: 'modelChange'` extra.

I noticed, that it also does not behave as expected. Check this out https://stackblitz.com/edit/angular-yu7bzv-8etafq

### Steps:
* Fill out input 1 + input 2

### Expected
* Next Button is disabled --> since input 3 was not yet filled

### Actual
* Next Button is enabled --> onBlur of input 2 it becomes disabled, which is the correct, but it should be disabled right away

I think, this is the exact same problem I have with the differnet UI approach. In my case, control become visible instead of a button becoming active, but both check the validity state, which returns valid even though it should be invalid.

**Comment by aitboudad** [comment]
Checked on my side and I think the issue resides in `disabled` input which doesn't work as expected which seems an issue in Angular.

The form validity is updated on model change and returns the expected value. I've tried several approaches to solve it and surprisingly I've noticed that using `[attr.disabled]` instead of `[disabled]` work: https://stackblitz.com/edit/angular-yu7bzv-ncdquw

You may use it as a workaround for now and if you've time to report it to Angular that would be better.
